routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', 'AuthController@index')->name('auth.index');
Route::post('/login', 'AuthController@login')->name('auth.login');
Route::get('/logout', 'AuthController@logout')->name('auth.logout');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard.index');

    Route::group(['prefix' => 'program', 'as' => 'program.'], function () {
        Route::get('/','ProgramController@index')->name('index');
        Route::get('/new','ProgramController@new')->name('new');
        Route::get('/edit/{id}','ProgramController@edit')->name('edit');
        Route::post('/store','ProgramController@store')->name('store');
        Route::post('/update','ProgramController@update')->name('update');
        Route::delete('/delete','ProgramController@delete')->name('delete');
    });

    Route::group(['prefix' => 'program-kategori', 'as' => 'program.kategori.'], function () {
        Route::get('/','ProgramKategoriController@index')->name('index');
        Route::get('/new','ProgramKategoriController@new')->name('new');
        Route::get('/edit/{id}','ProgramKategoriController@edit')->name('edit');
        Route::post('/store','ProgramKategoriController@store')->name('store');
        Route::post('/update','ProgramKategoriController@update')->name('update');
        Route::delete('/delete','ProgramKategoriController@delete')->name('delete');
    });

    Route::group(['prefix' => 'program-sub-kategori', 'as' => 'program.sub_kategori.'], function () {
        Route::get('/','ProgramSubKategoriController@index')->name('index');
        Route::get('/new','ProgramSubKategoriController@new')->name('new');
        Route::get('/edit/{id}','ProgramSubKategoriController@edit')->name('edit');
        Route::post('/kategori-list','ProgramSubKategoriController@kategoriList')->name('kategori-list');
        Route::post('/store','ProgramSubKategoriController@store')->name('store');
        Route::post('/update','ProgramSubKategoriController@update')->name('update');
        Route::delete('/delete','ProgramSubKategoriController@delete')->name('delete');
    });

    Route::group(['prefix' => 'kegiatan', 'as' => 'kegiatan.'], function () {
        Route::get('/','KegiatanController@index')->name('index');
        Route::get('/new','KegiatanController@new')->name('new');
        Route::get('/edit/{id}','KegiatanController@edit')->name('edit');
        Route::get('/print/{id}','KegiatanController@print')->name('print');
        Route::post('/store','KegiatanController@store')->name('store');
        Route::post('/update','KegiatanController@update')->name('update');
        Route::post('/kategori-list','KegiatanController@kategoriList')->name('kategori-list');
        Route::post('/sub-kategori-list','KegiatanController@subKategoriList')->name('sub-kategori-list');
        Route::delete('/delete','KegiatanController@delete')->name('delete');

        Route::get('/{kegiatan_id}/capaian','CapaianKegiatanController@index')->name('capaian.index');
        Route::get('/{kegiatan_id}/capaian/new','CapaianKegiatanController@new')->name('capaian.new');
        Route::get('/{kegiatan_id}/capaian/edit/{id}','CapaianKegiatanController@edit')->name('capaian.edit');
        Route::post('/capaian-kegiatan/store','CapaianKegiatanController@store')->name('capaian.store');
        Route::post('/capaian-kegiatan/update','CapaianKegiatanController@update')->name('capaian.update');
        Route::delete('/capaian-kegiatan/delete','CapaianKegiatanController@delete')->name('capaian.delete');

        Route::get('/{kegiatan_id}/target','TargetKegiatanController@index')->name('target.index');
        Route::get('/{kegiatan_id}/target/new','TargetKegiatanController@new')->name('target.new');
        Route::get('/{kegiatan_id}/target/edit/{id}','TargetKegiatanController@edit')->name('target.edit');
        Route::post('/target-kegiatan/store','TargetKegiatanController@store')->name('target.store');
        Route::post('/target-kegiatan/update','TargetKegiatanController@update')->name('target.update');
        Route::delete('/target-kegiatan/delete','TargetKegiatanController@delete')->name('target.delete');

        Route::get('/{kegiatan_id}/realisasi','RealisasiKegiatanController@index')->name('realisasi.index');
        Route::get('/{kegiatan_id}/realisasi/new','RealisasiKegiatanController@new')->name('realisasi.new');
        Route::get('/{kegiatan_id}/realisasi/edit/{id}','RealisasiKegiatanController@edit')->name('realisasi.edit');
        Route::post('/realisasi-kegiatan/store','RealisasiKegiatanController@store')->name('realisasi.store');
        Route::post('/realisasi-kegiatan/update','RealisasiKegiatanController@update')->name('realisasi.update');
        Route::delete('/realisasi-kegiatan/delete','RealisasiKegiatanController@delete')->name('realisasi.delete');

        Route::get('/{kegiatan_id}/tahapan','TahapanKegiatanController@index')->name('tahapan.index');
        Route::get('/{kegiatan_id}/tahapan/new','TahapanKegiatanController@new')->name('tahapan.new');
        Route::get('/{kegiatan_id}/tahapan/edit/{id}','TahapanKegiatanController@edit')->name('tahapan.edit');
        Route::post('/tahapan-kegiatan/store','TahapanKegiatanController@store')->name('tahapan.store');
        Route::post('/tahapan-kegiatan/update','TahapanKegiatanController@update')->name('tahapan.update');
        Route::delete('/tahapan-kegiatan/delete','TahapanKegiatanController@delete')->name('tahapan.delete');

    });
});

resources/views/app/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
  <title>PUPR Apps</title>

  <!-- General CSS Files -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

  <!-- CSS Libraries -->

  <!-- Template CSS -->
  <link rel="stylesheet" href="{{ asset('css/jquery.dataTables.min.css') }}">
	<link rel="stylesheet" href="{{ asset('css/toastr.min.css') }}">
  <link rel="stylesheet" href="{{ asset('css/style.css') }}">
  <link rel="stylesheet" href="{{ asset('css/components.css') }}">
  
</head>

<body>
  <div id="app">
    <div class="main-wrapper">
      <div class="navbar-bg"></div>
      <nav class="navbar navbar-expand-lg main-navbar">
        <form class="form-inline mr-auto">
          <ul class="navbar-nav mr-3">
            <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
            <li><a href="#" data-toggle="search" class="nav-link nav-link-lg d-sm-none"><i class="fas fa-search"></i></a></li>
          </ul>
        </form>
        <ul class="navbar-nav navbar-right">
            <li class="dropdown">
                <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                    <img alt="image" src="{{ asset('img/avatar/avatar-1.png') }}" class="rounded-circle mr-1">
                    <div class="d-sm-none d-lg-inline-block">{{ Auth::user()->name }}</div>
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                    <a href="#" class="dropdown-item has-icon">
                        <i class="far fa-user"></i> Profile
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="{{ route('auth.logout') }}" class="dropdown-item has-icon text-danger">
                        <i class="fas fa-sign-out-alt"></i> Logout
                    </a>
                </div>
            </li>
        </ul>
      </nav>
      <div class="main-sidebar">
        <aside id="sidebar-wrapper">
            <div class="sidebar-brand">
                <img src="{{ asset('img/logo.png') }}" alt="logo" width="80" class="shadow-light rounded-circle" style="width: 15%;">
                <a href="{{ route('dashboard.index') }}">PUPR</a>
            </div>
            <div class="sidebar-brand sidebar-brand-sm">
                <a href="{{ route('dashboard.index') }}">PU</a>
            </div>
            @include('app.layouts.sidebar')
        </aside>
      </div>

      <!-- Main Content -->
      <div class="main-content">
        <section class="section">
          <div class="section-header">
            <h1>@yield('title')</h1>
          </div>

          <div class="section-body">
              @if ($errors->any())
                  <div class="alert alert-danger">
                      <ul>
                          @foreach ($errors->all() as $error)
                              <li>{{ $error }}</li>
                          @endforeach
                      </ul>
                  </div>
              @endif
              @if (session('danger'))
                  <div class="alert alert-danger">
                      {{ session('danger') }}
                  </div>
              @endif
              @if (session('danger-with-link'))
                  <div class="alert alert-danger">
                      {!! session('danger-with-link') !!}
                  </div>
              @endif
              @if (session('success'))
                  <div class="alert alert-success">
                      {{ session('success') }}
                  </div>
              @endif
              @yield('content')
          </div>
        </section>
      </div>
      <footer class="main-footer">
        <div class="footer-left">
          Copyright &copy; {{ date('Y') }}
        </div>
        <div class="footer-right">
          2.3.0
        </div>
      </footer>
    </div>
  </div>

  <!-- General JS Scripts -->
  <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
  <script src="{{ asset('js/stisla.js') }}"></script>

  <!-- JS Libraies -->

  <!-- Template JS File -->
  <script src="{{ asset('js/jquery.dataTables.min.js') }}"></script>
	<script src="{{ asset('js/toastr.min.js') }}"></script>
	<script src="{{ asset('js/parsley.min.js') }}"></script>
  <script src="{{ asset('js/scripts.js') }}"></script>
  <script src="{{ asset('js/custom.js') }}"></script>
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
  @stack('scripts')

  <!-- Page Specific JS File -->
</body>
</html>

resources/views/app/layouts/sidebar.blade.php
<ul class="sidebar-menu">
    <li class="menu-header">Menu</li>
    <li>
        <a class="nav-link" href="#">
            <i class="fas fa-home"></i> <span>Dashboard</span>
        </a>
    </li>
    <li class="nav-item dropdown">
        <a href="#" class="nav-link has-dropdown"><i class="fas fa-fire"></i><span>Program</span></a>
        <ul class="dropdown-menu">
          <li><a class="nav-link" href="{{ route('program.index') }}">List</a></li>
          <li><a class="nav-link" href="{{ route('program.kategori.index') }}">Kategori</a></li>
          <li><a class="nav-link" href="{{ route('program.sub_kategori.index') }}">Sub Kategori</a></li>
        </ul>
    </li>
    <li>
        <a class="nav-link" href="{{ route('kegiatan.index')}}">
            <i class="fas fa-fire"></i> <span>Kegiatan</span>
        </a>
    </li>
</ul>