routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', 'AuthController@index')->name('auth.index');
Route::post('/login', 'AuthController@login')->name('auth.login');
Route::get('/logout', 'AuthController@logout')->name('auth.logout');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard.index');

    Route::group(['prefix' => 'program', 'as' => 'program.'], function () {
        Route::get('/','ProgramController@index')->name('index');
        Route::get('/new','ProgramController@new')->name('new');
        Route::get('/edit/{id}','ProgramController@edit')->name('edit');
        Route::post('/store','ProgramController@store')->name('store');
        Route::post('/update','ProgramController@update')->name('update');
        Route::delete('/delete','ProgramController@delete')->name('delete');
    });

    Route::group(['prefix' => 'program-kategori', 'as' => 'program.kategori.'], function () {
        Route::get('/','ProgramKategoriController@index')->name('index');
        Route::get('/new','ProgramKategoriController@new')->name('new');
        Route::get('/edit/{id}','ProgramKategoriController@edit')->name('edit');
        Route::post('/store','ProgramKategoriController@store')->name('store');
        Route::post('/update','ProgramKategoriController@update')->name('update');
        Route::delete('/delete','ProgramKategoriController@delete')->name('delete');
    });

    Route::group(['prefix' => 'program-sub-kategori', 'as' => 'program.sub_kategori.'], function () {
        Route::get('/','ProgramSubKategoriController@index')->name('index');
        Route::get('/new','ProgramSubKategoriController@new')->name('new');
        Route::get('/edit/{id}','ProgramSubKategoriController@edit')->name('edit');
        Route::post('/kategori-list','ProgramSubKategoriController@kategoriList')->name('kategori-list');
        Route::post('/store','ProgramSubKategoriController@store')->name('store');
        Route::post('/update','ProgramSubKategoriController@update')->name('update');
        Route::delete('/delete','ProgramSubKategoriController@delete')->name('delete');
    });

    Route::group(['prefix' => 'kegiatan', 'as' => 'kegiatan.'], function () {
        Route::get('/','KegiatanController@index')->name('index');
        Route::get('/new','KegiatanController@new')->name('new');
        Route::get('/edit/{id}','KegiatanController@edit')->name('edit');
        Route::get('/print/{id}','KegiatanController@print')->name('print');
        Route::post('/store','KegiatanController@store')->name('store');
        Route::post('/update','KegiatanController@update')->name('update');
        Route::post('/kategori-list','KegiatanController@kategoriList')->name('kategori-list');
        Route::post('/sub-kategori-list','KegiatanController@subKategoriList')->name('sub-kategori-list');
        Route::delete('/delete','KegiatanController@delete')->name('delete');

        Route::get('/{kegiatan_id}/capaian','CapaianKegiatanController@index')->name('capaian.index');
        Route::get('/{kegiatan_id}/capaian/new','CapaianKegiatanController@new')->name('capaian.new');
        Route::get('/{kegiatan_id}/capaian/edit/{id}','CapaianKegiatanController@edit')->name('capaian.edit');
        Route::post('/capaian-kegiatan/store','CapaianKegiatanController@store')->name('capaian.store');
        Route::post('/capaian-kegiatan/update','CapaianKegiatanController@update')->name('capaian.update');
        Route::delete('/capaian-kegiatan/delete','CapaianKegiatanController@delete')->name('capaian.delete');

        Route::get('/{kegiatan_id}/target','TargetKegiatanController@index')->name('target.index');
        Route::get('/{kegiatan_id}/target/new','TargetKegiatanController@new')->name('target.new');
        Route::get('/{kegiatan_id}/target/edit/{id}','TargetKegiatanController@edit')->name('target.edit');
        Route::post('/target-kegiatan/store','TargetKegiatanController@store')->name('target.store');
        Route::post('/target-kegiatan/update','TargetKegiatanController@update')->name('target.update');
        Route::delete('/target-kegiatan/delete','TargetKegiatanController@delete')->name('target.delete');

        Route::get('/{kegiatan_id}/realisasi','RealisasiKegiatanController@index')->name('realisasi.index');
        Route::get('/{kegiatan_id}/realisasi/new','RealisasiKegiatanController@new')->name('realisasi.new');
        Route::get('/{kegiatan_id}/realisasi/edit/{id}','RealisasiKegiatanController@edit')->name('realisasi.edit');
        Route::post('/realisasi-kegiatan/store','RealisasiKegiatanController@store')->name('realisasi.store');
        Route::post('/realisasi-kegiatan/update','RealisasiKegiatanController@update')->name('realisasi.update');
        Route::delete('/realisasi-kegiatan/delete','RealisasiKegiatanController@delete')->name('realisasi.delete');

        Route::get('/{kegiatan_id}/tahapan','TahapanKegiatanController@index')->name('tahapan.index');
        Route::get('/{kegiatan_id}/tahapan/new','TahapanKegiatanController@new')->name('tahapan.new');
        Route::get('/{kegiatan_id}/tahapan/edit/{id}','TahapanKegiatanController@edit')->name('tahapan.edit');
        Route::post('/tahapan-kegiatan/store','TahapanKegiatanController@store')->name('tahapan.store');
        Route::post('/tahapan-kegiatan/update','TahapanKegiatanController@update')->name('tahapan.update');
        Route::delete('/tahapan-kegiatan/delete','TahapanKegiatanController@delete')->name('tahapan.delete');

    });
});

app/Models/ProgramSubKategori.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ProgramSubKategori extends Model
{
    protected $table = 'program_sub_kategoris';

    protected $fillable = [
        "kode","nama","program_kategori_id"
    ];

    public function kategori()
    {
        return $this->belongsTo(Program::class, "program_kategori_id");
    }
}

app/Http/Controllers/ProgramSubKategoriController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\ProgramKategori;
use App\Models\ProgramSubKategori;
use App\Models\Program;
use DataTables;
use Yajra\DataTables\Html\Builder;
use Validator;

class ProgramSubKategoriController extends Controller
{
    public function index(Builder $builder)
    {
        if (request()->ajax()) {
			return $this->datatables();
        }

        $html = $this->builder($builder)
			->minifiedAjax()
            ->responsive()
            ->autoWidth(false);

        return view('app.pages.program_sub_kategori.index')->with([
            'html' => $html
        ]);
    }

    public function datatables()
	{
        $table = new ProgramSubKategori;
        return datatables($table->query())
        ->addIndexColumn()
        ->addColumn('kategori', function($model) {
            return $model->kategori->nama;
        })
        ->addColumn('action', function($model) {
            return "
                <div class='btn-group'>
                    <a class='btn btn-sm btn-primary' href='".route('program.sub_kategori.edit', $model->id)."'><i class='fas fa-edit'></i></a>
                    <button class='btn btn-sm btn-danger btn-delete'>
                        <i class='fas fa-trash'></i>
                    </button>
                </div>
            ";
            return "";
        })
        ->toJson();
    }

    public function builder(Builder $builder)
	{
		return $builder->columns([
            [
                'data' => 'DT_RowIndex','title' => '#',
                'orderable' => false,'searchable' => false,
                'width' => '24px'
            ],
            [
                'data' => 'kode', 'title' => 'Kode'
            ],
            [
                'data' => 'nama', 'title' => 'Nama'
            ],
            [
                'data' => 'kategori', 'title' => 'Kategori'
            ],
            [
                'data' => 'action','title' => 'Action',
                'width' => '120px','class' => 'text-center',
                'orderable' => false,
                'searchable' => false
            ]
		]);
    }

    public function new()
    {
        $programs = Program::pluck('nama','id');
        return view('app.pages.program_sub_kategori.new')
            ->with([
                "programs" => $programs
            ]);
    }

    public function edit($id)
    {
        $data = ProgramSubKategori::findOrFail($id);
        $programs = Program::pluck('nama','id');
        return view('app.pages.program_sub_kategori.edit')
            ->with([
                "data" => $data,
                "programs" => $programs
            ]);
    }

    public function store(Request $request)
    {
        $store = ProgramSubKategori::create([
            "kode" => $request->kode,
            "nama" => $request->nama,
            "program_kategori_id" => $request->program_kategori_id,
        ]);

        return $store ? redirect()->route('program.sub_kategori.index')->with('success','Data berhasil disimpan')
            : redirect()->route('program.kategori.index')->with('danger','Data gagal disimpan');
    }

    public function update(Request $request)
    {
        $data = ProgramSubKategori::findOrFail($request->id);
        $data->kode = $request->kode;
        $data->nama = $request->nama;
        $data->program_kategori_id = $request->program_kategori_id;
        $store = $data->save();

        return $store ? redirect()->route('program.sub_kategori.index')->with('success','Data berhasil disimpan')
            : redirect()->route('program.sub_kategori.index')->with('danger','Data gagal disimpan');
    }

    public function delete(Request $request)
    {
        $data = ProgramSubKategori::where('id', $request->id)->firstOrFail();
        $delete = $data->delete();
        
        return $delete ? response()->json(['success' => true,'message'=>'Data berhasil dihapus'])
        : response()->json(['success' => false,'message'=>'Data gagal dihapus']);
    }

    public function kategoriList(Request $request)
    {
        $datas = ProgramKategori::where('program_id', $request->program_id)->get();

        return response()->json([
            "status" => true,
            "data" => $datas
        ]);
    }
}

resources/views/app/pages/program_sub_kategori/edit.blade.php
@extends('app.layouts.master')
@section('title','Sunting Data Program Sub Kategori')
@section('content')

<div class="row">
    <div class="col-12 col-md-12 col-lg-12">
        {!! Form::open(['id' => 'form','route' => 'program.sub_kategori.update']) !!}
            {!! Form::hidden('id', $data->id, []) !!}
        <div class="card">
            <div class="card-header">
                Form Isian
            </div>
            <div class="card-body">
                <div class="form-group">
                    <label for="">Program</label>
                    {!! Form::select('program_id', $programs, null, ['class' => 'form-control','required',
                        'placeholder' => 'Pilih salah satu', 'id' => 'program_id']) !!}
                </div>
                <div class="form-group">
                    <label for="">Program kategori</label>
                    {!! Form::select('program_kategori_id', [], $data->program_kategori_id, ['class' => 'form-control','required',
                        'placeholder' => 'Pilih salah satu','id' => 'program_kategori_id']) !!}
                </div>
                <div class="form-group">
                    <label for="">Kode</label>
                    {!! Form::text('kode', $data->kode, ['class' => 'form-control','required']) !!}
                </div>
                <div class="form-group">
                    <label for="">Nama</label>
                    {!! Form::text('nama', $data->nama, ['class' => 'form-control','required']) !!}
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
                <a href="{{ route('program.sub_kategori.index') }}" class="btn btn-default">Cancel</a>
            </div>
        </div>
        {!! Form::close() !!}
    </div>
</div>

@endsection
@push('scripts')
    <script>
        $(document).ready(function() {
            $("#form").parsley()

            $("#program_id").on('change', function (e) {
                $.ajax({
                    method: 'POST',
                    headers: {
                        'X-CSRF-Token': "{{ csrf_token() }}"
                    },
                    url: "{{ route('program.sub_kategori.kategori-list') }}",
                    data: {
                        program_id : $(this).val()
                    },
                    success: function(result) {
                        $("#program_kategori_id").empty();
                        $("#program_kategori_id").append(`<option value="">
                            Pilih Salah Satu
                        </option>`);

                        result.data.map(v => {
                            $("#program_kategori_id").append(`<option value="${v.id}">
                                ${v.nama}
                            </option>`);
                        })
                    },
                    error: function(err){
                        console.log(error)
                    }
                });
            })
        })
    </script>
@endpush

resources/views/app/pages/program_sub_kategori/index.blade.php
@extends('app.layouts.master')
@section('title','Data Program Sub Kategori')
@section('content')

<div class="row">
    <div class="col-12 col-md-12 col-lg-12">
        <div class="card">
            <div class="card-header">
                <a href="{{ route('program.sub_kategori.new') }}" class="btn btn-primary">Tambah Data</a>
            </div>
            <div class="card-body">
                {!! $html->table() !!}
            </div>
        </div>
    </div>
</div>

@endsection
@push('scripts')
    {!! $html->scripts() !!}
    <script>
        $(document).ready(function() {
            $('table#dataTableBuilder tbody').on( 'click', 'td button', function (e) {
                var mode = $(this).attr("data-mode");
                var parent = $(this).parent().get( 0 );
                var parent1 = $(parent).parent().get( 0 );
                var row = $('#dataTableBuilder').DataTable().row(parent1);
                var data = row.data();
                if($(this).hasClass('btn-delete') ){
                    Swal.fire({
                        title: 'Apakah Anda Yakin Untuk Menghapus Data Ini?',
                        icon: 'warning',
                        showCancelButton: true,
                        confirmButtonText: 'Yakin',
                        cancelButtonText: 'Tidak'
                    }).then((result) => {
                        if (result.value) {
                            
                            const form = {
                                id : data.id,
                            }
                            $.ajax({
                                method: 'DELETE',
                                headers: {
                                    'X-CSRF-Token': "{{ csrf_token() }}"
                                },
                                url: "{{ route('program.sub_kategori.delete') }}",
                                dataType: 'JSON',
                                cache: false,
                                data: form,
                                success: function(result) {
                                    toastr.success(result.message, 'Success !')
                                    $('#dataTableBuilder').DataTable().ajax.reload();
                                },
                                error: function(err){
                                    toastr.error(err.responseJSON.message, 'Error !')
                                    $('#dataTableBuilder').DataTable().ajax.reload();
                                }
                            });

                        } else {
                        }
                    })
                }   
            
            })
        })
    </script>
@endpush

resources/views/app/pages/program_sub_kategori/new.blade.php
@extends('app.layouts.master')
@section('title','Tambah Data Program Sub Kategori Baru')
@section('content')

<div class="row">
    <div class="col-12 col-md-12 col-lg-12">
        {!! Form::open(['id' => 'form','route' => 'program.sub_kategori.store']) !!}
        <div class="card">
            <div class="card-header">
                Form Isian
            </div>
            <div class="card-body">
                <div class="form-group">
                    <label for="">Program</label>
                    {!! Form::select('program_id', $programs, null, ['class' => 'form-control','required',
                        'placeholder' => 'Pilih salah satu', 'id' => 'program_id']) !!}
                </div>
                <div class="form-group">
                    <label for="">Program kategori</label>
                    {!! Form::select('program_kategori_id', [], null, ['class' => 'form-control','required',
                        'placeholder' => 'Pilih salah satu','id' => 'program_kategori_id']) !!}
                </div>
                <div class="form-group">
                    <label for="">Kode</label>
                    {!! Form::text('kode', null, ['class' => 'form-control','required']) !!}
                </div>
                <div class="form-group">
                    <label for="">Nama</label>
                    {!! Form::text('nama', null, ['class' => 'form-control','required']) !!}
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
                <a href="{{ route('program.sub_kategori.index') }}" class="btn btn-default">Cancel</a>
            </div>
        </div>
        {!! Form::close() !!}
    </div>
</div>

@endsection
@push('scripts')
    <script>
        $(document).ready(function() {
            $("#form").parsley()

            $("#program_id").on('change', function (e) {
                $.ajax({
                    method: 'POST',
                    headers: {
                        'X-CSRF-Token': "{{ csrf_token() }}"
                    },
                    url: "{{ route('program.sub_kategori.kategori-list') }}",
                    data: {
                        program_id : $(this).val()
                    },
                    success: function(result) {
                        $("#program_kategori_id").empty();
                        $("#program_kategori_id").append(`<option value="">
                            Pilih Salah Satu
                        </option>`);

                        result.data.map(v => {
                            $("#program_kategori_id").append(`<option value="${v.id}">
                                ${v.nama}
                            </option>`);
                        })
                    },
                    error: function(err){
                        console.log(error)
                    }
                });
            })
        })
    </script>
@endpush